### ISSUE TITLE
builds failing with 'ModuleNotFoundError: No module named 'pip.pep425tags'

### ISSUE THREAD

**Issue by jswhit** [MacPython/netcdf4-python-wheels#8]
Traceback (most recent call last):
  File "/io/multibuild/supported_wheels.py", line 15, in <module>
    from pip.pep425tags import get_supported
ModuleNotFoundError: No module named 'pip.pep425tags'

@matthew-brett - I assume I need to upgrade something..?

**Comment by mattip** [comment]
I think if you `cd multibuild; git pull` you should get the latest `devel` branch of  multibuild. This [was updated](https://github.com/matthew-brett/multibuild/blame/devel/supported_wheels.py) a few months ago.

**Comment by matthew-brett** [comment]
What @mattip said !

**Comment by jswhit** [comment]
Thanks - updating to the devel branch (instead of master) got it past that one. Now it's failing to upload the wheels (see https://travis-ci.org/github/MacPython/netcdf4-python-wheels/jobs/710844543).

**Comment by mattip** [comment]
Copying from [this comment](https://github.com/MacPython/kiwisolver-wheels/issues/9#issue-651367922):

As per matthew-brett/multibuild#304, projects should not upload to rackspace since this is no longer free. Over at numpy-wheels, we chose to use anaconda.org for [staging](https://anaconda.org/multibuild-wheels-staging) and [weekly builds](https://anaconda.org/scipy-wheels-nightly). Cython chose to upload them to github as [release packages](https://github.com/MacPython/cython-wheels/releases). One advantage to using a shared location is that any of the wheels in that location can be installed with a single -i https://pypi.anaconda.org/scipy-wheels-nightly/simple argument to pip.

If you choose the anaconda route, I can set you up with a token to the anaconda staging areas, and help you do something like the [numpy-wheels](https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml#L99) upload code.

If you choose the github route, [here is what cython did](https://github.com/MacPython/cython-wheels/blob/master/appveyor.yml#L118) to upload there

**Comment by jswhit** [comment]
@mattip - I am interested in going the anaconda routine for this project, as well as for cftime-wheels.
